#!/bin/bash

numRuns=1

transport=basic+dpdk

numObjects=340000000
objectSize=100

function run() {
    tag=$1
    shift

    ./scripts/clusterperf.py migrateLoaded \
            -T $transport \
            --workload=YCSB-B \
            --loadPct=60 \
            --seconds=90 \
            --timeout=3240 \
            --migratePercentage=50 \
            --size=$objectSize \
            --numObjects=$numObjects \
            --masterArgs='--totalMasterMemory=61000 --segmentFrames=46080 --maxCores=10 --maxNonVolatileBuffers=0 -d' \
            --verbose \
            -r 3 \
            --fullSamples \
            --servers=14 \
            --clients=8 \
            --useRocksteady

    mkdir -p logs/rocksteady/$tag/
    cp -r logs/latest/* logs/rocksteady/$tag/
}

make clean
make -j8 DEBUG=no DPDK=yes DPDK_DIR=dpdk

for runNum in `seq 1 $numRuns`
do
    run rocksteady$runNum
done
