#!/bin/bash

# numRuns=10
numRuns=1

transport=basic+dpdk

# numObjects=300000000
numObjects=30000000
objectSize=100

function run() {
    tag=$1
    shift

    # pdsh -w node-[0-23] \
    #         "echo 3 | sudo tee --append /proc/sys/vm/drop_caches > /dev/null"
    # sleep 120

    ./scripts/clusterperf.py migrateLoaded \
            -T $transport \
            --workload=YCSB-B \
            --seconds=120 \
            --timeout=3240 \
            --migratePercentage=50 \
            --size=$objectSize \
            --numObjects=$numObjects \
            --masterArgs='--totalMasterMemory=57344 --segmentFrames=46080 --maxCores=9 --maxNonVolatileBuffers=0 -d' \
            --verbose \
            -r 0 \
            --servers=4 \
            --clients=3 \
            --useRocksteady \
            --dpdkPort=0 \
            --superuser \
            # --loadPct=55 \
            # --fullSamples \
            # --logLevel=DEBUG

    mkdir -p logs/rocksteady/$tag/
    cp -r logs/latest/* logs/rocksteady/$tag/
}

# make clean
# make -j8 DEBUG=no DPDK=yes DPDK_DIR=dpdk

for runNum in `seq 1 $numRuns`
do
    run rocksteady$runNum
done
